mode: rule
mixed-port: 7890
allow-lan: true
log-level: debug
ipv6: false
external-controller: 0.0.0.0:9090
tcp-concurrent: true

tun:
  enable: true
  stack: gvisor
  device: mihomo0
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  default-nameserver:
    - 8.8.8.8
    - 114.114.114.114
    - 223.5.5.5
  nameserver:
    - 8.8.8.8
    - 114.114.114.114
    - 223.5.5.5

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Auto
      - Fallback
    use:
      - sub
  - name: Auto
    type: url-test
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    use:
      - sub
  - name: Fallback
    type: fallback
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    use:
      - sub

proxy-providers:
  sub:
    type: http
    url: 'https://sub.xeton.dev/sub?target=clash&list=true&url=ENCODE'
    path: sub.yaml
    interval: 3600
    health-check:
      enable: true
      url: 'https://www.gstatic.com/generate_204'
      interval: 300

rules:
  - RULE-SET,Advertising,REJECT
  - RULE-SET,Proxy,Proxy
  - RULE-SET,ChinaMax,DIRECT
  - RULE-SET,Lan,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy

rule-providers:
  Lan:
    behavior: classical
    type: http
    url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.yaml'
    interval: 86400
    path: Lan.yaml
  
  Advertising:
    behavior: classical
    type: http
    url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising_Classical.yaml'
    interval: 86400
    path: Advertising.yaml
  
  Proxy:
    behavior: classical
    type: http
    url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Proxy/Proxy_Classical.yaml'
    interval: 86400
    path: Proxy.yaml
  
  ChinaMax:
    behavior: classical
    type: http
    url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml'
    interval: 86400
    path: ChinaMax.yaml
